Repository openscad/openscad, pull requests merged in 2018-11, with the labels that each got.

#2540 AppVeyor integration
  appveyor.yml
  features/scintilla.prf
  scripts/msys2-install-dependencies.sh
  tests/CMakeLists.txt
  tests/test_cmdline_tool.py
  tests/test_pretty_print.py
Labels: Build tweaks, Discussion

#2549 Enable QtGamepad for macOS
  scripts/macosx-build-dependencies.sh
Labels: Inputdriver, OS: Mac OS X

#1802 3mf Import/Export
  .circleci/config.yml
  .gitignore
  Info.plist
  features/lib3mf.prf
  features/sparkle.prf
  images/3MF-white.png
  images/3MF.png
  openscad.pro
  openscad.qrc
  scripts/macosx-build-dependencies.sh
  scripts/macosx-build-homebrew.sh
  scripts/macosx-sanity-check.py
  scripts/mingw-x-build-dependencies.sh
  src/LibraryInfo.cc
  src/MainWindow.h
  src/MainWindow.ui
  src/cgal.h
  src/export.cc
  src/export.h
  src/export_3mf.cc
  src/feature.cc
  src/feature.h
  src/import.cc
  src/import_3mf.cc
  src/importnode.h
  src/mainwin.cc
  src/openscad.cc
  testdata/scad/3D/features/import.3mf
  testdata/scad/3mf/3mf-export.scad
  testdata/scad/templates/import_3mf-tests-template.scad
  tests/CMakeLists.txt
  tests/FindLib3MF.cmake
  tests/export_import_pngtest.py
  tests/regression/3mfexport/3mf-export-expected.3mf
  tests/regression/cgalpngtest/import_3mf-tests-expected.png
  tests/regression/dumptest/import_3mf-tests-expected.csg
  tests/regression/opencsgtest/import_3mf-tests-expected.png
  tests/regression/throwntogethertest/import_3mf-tests-expected.png
  tests/test_cmdline_tool.py
  tests/test_pretty_print.py
Labels: Needs minor work

#2558 Travis: Add support for Ubuntu 16.04
  .travis.yml
Labels: Build tweaks
