Repository openscad/openscad, pull requests merged in 2018-09, with the labels that each got.

#2456 osx high Sierra fixes
  scripts/macosx-build-dependencies.sh
Labels: Build tweaks, OS: Mac OS X

#2452 Mxe gcc7
  .gitignore
  .qmake.cache
  boost.pri
  cgal.pri
  common.pri
  defaults.pri
  features/boost.prf
  features/cgal.prf
  features/eigen.prf
  features/fontconfig.prf
  features/freetype.prf
  features/gettext.prf
  features/glew.prf
  features/glib-2.0.prf
  features/harfbuzz.prf
  features/libxml2.prf
  features/libzip.prf
  features/opencsg.prf
  features/qscintilla2-priv.prf
  features/scintilla.prf
  features/sparkle.prf
  glew.pri
  mingw-cross-env.pri
  opencsg.pri
  openscad.pro
  scintilla.pri
  scripts/mingw-x-build-dependencies.sh
  scripts/release-common.sh
  scripts/setenv-mingw-xbuild.sh
  sparkle.pri
Labels: Build tweaks

#2455 making updateFindIndicators side effect free
  src/editor.h
  src/legacyeditor.cc
  src/legacyeditor.h
  src/mainwin.cc
  src/scintillaeditor.cpp
  src/scintillaeditor.h
Labels: GUI, Scintilla

#2478 save hidden variables, but to not apply them (see #2450)
  src/parameter/ParameterWidget.cc
  src/parameter/parameterextractor.cpp
Labels: Customizer

#2479 adding a "design default values" parameter set
  src/mainwin.cc
  src/parameter/ParameterWidget.cc
  src/parameter/ParameterWidget.h
  src/parameter/ParameterWidget.ui
Labels: Customizer

#2481 customizer: check if a parameter set name already exists and ask before overwritting
  src/parameter/ParameterWidget.cc
  src/parameter/ParameterWidget.h
  src/parameter/parameterset.cpp
  src/parameter/parameterset.h
Labels: Customizer

#2483 customizer: add the json file to the hidden backup
  src/mainwin.cc
  src/parameter/ParameterWidget.cc
  src/parameter/ParameterWidget.h
Labels: Customizer

#2448 Translation context
  doc/translation.txt
  locale/cs.po
  locale/de.po
  locale/es.po
  locale/fr.po
  locale/openscad.pot
  locale/pl.po
  locale/ru.po
  scripts/translation-update.sh
  src/Preferences.ui
Labels: internationalization

#2485 make the comboBoxPreset editable
  src/parameter/ParameterWidget.cc
  src/parameter/ParameterWidget.h
  src/parameter/ParameterWidget.ui
Labels: Customizer

#2460 warn, when a variable from the root module is overwriten in the root module
  src/ModuleCache.cc
  src/lexer.l
  src/mainwin.cc
  src/openscad.cc
  src/parser.y
  tests/regression/echotest/scope-assignment-tests-expected.echo
  tests/regression/echotest/search-tests-expected.echo
  tests/regression/echotest/value-reassignment-tests-expected.echo
  tests/regression/echotest/value-reassignment-tests2-expected.echo
Labels: parser
