Repository openscad/openscad, pull requests merged in 2024-04, with the labels that each got.

#5102 Fix win installer properties
  .gitignore
  CMakeLists.txt
  cmake/Modules/openscad_cpack.cmake.in
  cmake/nsis/LogicLib.nsh
  cmake/nsis/extra-install-commands.nsh.in
  cmake/nsis/extra-uninstall-commands.nsh.in
  cmake/nsis/mingw-file-association.nsh
  cmake/nsis/x64.nsh
  resources/openscad_win32-nightly.rc
  resources/openscad_win32-nightly.rc.in
  resources/openscad_win32.rc
  resources/openscad_win32.rc.in
Labels: PR: Maintenance

#5088 Split 3MF implementation into separate files per API version
  CMakeLists.txt
  src/io/export_3mf_dummy.cc
  src/io/export_3mf_v1.cc
  src/io/export_3mf_v2.cc
  src/io/import_3mf_dummy.cc
  src/io/import_3mf_v1.cc
  src/io/import_3mf_v2.cc
Labels: PR: Maintenance

#5104 Bump LodePNG to 20230410.
  src/ext/lodepng/lodepng.cpp
  src/ext/lodepng/lodepng.h
Labels: PR: Maintenance

#5103 Use saveGeometry() instead of trying to restore size/position separately.
  src/gui/MainWindow.cc
Labels: PR: Bugfix

#5105 Fix tooltip for offset().
  src/core/OffsetNode.cc
Labels: PR: Bugfix

#5108 Remove obsolete libuuid; lib3mf no longer needs it
  scripts/macosx-build-dependencies.sh
Labels: PR: Maintenance

#5107 Support horizontal and vertical layouts (fixes #4706).
  src/gui/ViewportControl.cc
  src/gui/ViewportControl.h
  src/gui/ViewportControl.ui
Labels: PR: Enhancement
